version: '3'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: lolkek
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "admin" ]

volumes:
  postgres:
